eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
  client:
    service-url:
      defaultZone: http://user:password@registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

authserver:
    hostname: auth-service
    port: 5000
    contextPath: /auth

management:
  security:
    enabled: false
  context-path: /mgmt

security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}
      filter-order: 3
      
server:
  context-path: /auth
  port: 5000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    ddl-auto: update
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update